// jobData.js

const jobData = [
  {
    company_name: "Adobe",
    location: "Bangalore",
    job_title: "Cloud Engineer",
    job_description:
      "Design and deploy cloud-based solutions for various products.",
    no_of_positions: 3,
    employment_type: "Full-time",
    years_of_experience: 4,
    salary: 2000000,
    work_mode: "Hybrid",
  },
  {
    company_name: "Amazon",
    location: "Chennai",
    job_title: "DevOps Engineer",
    job_description: "Automate and streamline cloud infrastructure processes.",
    no_of_positions: 4,
    employment_type: "Full-time",
    years_of_experience: 3,
    salary: 1500000,
    work_mode: "Hybrid",
  },
  {
    company_name: "AMD",
    location: "Pune",
    job_title: "Machine Learning Engineer",
    job_description:
      "Develop machine learning models for product optimization.",
    no_of_positions: 2,
    employment_type: "Full-time",
    years_of_experience: 4,
    salary: 2200000,
    work_mode: "Office",
  },
  {
    company_name: "Apple",
    location: "Bangalore",
    job_title: "Backend Engineer",
    job_description: "Design and maintain scalable backend systems for iCloud.",
    no_of_positions: 3,
    employment_type: "Full-time",
    years_of_experience: 4,
    salary: 2500000,
    work_mode: "Hybrid",
  },
  {
    company_name: "Flipkart",
    location: "Bangalore ",
    job_title: "Product Manager",
    job_description: "Manage and enhance product development roadmaps.",
    no_of_positions: 3,
    employment_type: "Full-time",
    years_of_experience: 5,
    salary: 2000000,
    work_mode: "Work from Home",
  },
  {
    company_name: "IBM",
    location: "Pune ",
    job_title: "Blockchain Developer",
    job_description:
      "Develop decentralized applications and blockchain-based solutions.",
    no_of_positions: 2,
    employment_type: "Full-time",
    years_of_experience: 3,
    salary: 2200000,
    work_mode: "Hybrid",
  },
  {
    company_name: "Meta",
    location: "Hyderabad ",
    job_title: "Security Engineer",
    job_description:
      "Secure and monitor infrastructure and systems against threats.",
    no_of_positions: 4,
    employment_type: "Full-time",
    years_of_experience: 5,
    salary: 2800000,
    work_mode: "Office",
  },
  {
    company_name: "Microsoft",
    location: "Bangalore ",
    job_title: "Data Engineer",
    job_description: "Build and maintain data pipelines for analytics.",
    no_of_positions: 5,
    employment_type: "Full-time",
    years_of_experience: 4,
    salary: 1800000,
    work_mode: "Hybrid",
  },
  {
    company_name: "Nvidia",
    location: "Chennai ",
    job_title: "AI/ML Research Scientist",
    job_description: "Research and implement AI models for advanced products.",
    no_of_positions: 3,
    employment_type: "Full-time",
    years_of_experience: 5,
    salary: 3000000,
    work_mode: "Hybrid",
  },
  {
    company_name: "Qualcomm",
    location: "Hyderabad ",
    job_title: "Embedded Systems Engineer",
    job_description: "Develop and optimize software for embedded systems.",
    no_of_positions: 3,
    employment_type: "Full-time",
    years_of_experience: 3,
    salary: 1800000,
    work_mode: "Office",
  },
  {
    company_name: "Adobe",
    location: "Noida ",
    job_title: "Data Engineer",
    job_description: "Design and build data pipelines for analytics.",
    no_of_positions: 4,
    employment_type: "Full-time",
    years_of_experience: 3,
    salary: 1400000,
    work_mode: "Hybrid",
  },
  {
    company_name: "Amazon",
    location: "Bangalore ",
    job_title: "Software Development Engineer",
    job_description: "Develop and maintain high-performance applications.",
    no_of_positions: 5,
    employment_type: "Full-time",
    years_of_experience: 3,
    salary: 1800000,
    work_mode: "Hybrid",
  },
  {
    company_name: "AMD",
    location: "Hyderabad ",
    job_title: "System Software Engineer",
    job_description: "Work on system-level optimizations for hardware.",
    no_of_positions: 2,
    employment_type: "Full-time",
    years_of_experience: 4,
    salary: 2000000,
    work_mode: "Office",
  },
  {
    company_name: "Apple",
    location: "Hyderabad ",
    job_title: "Machine Learning Engineer",
    job_description: "Build and deploy ML models for Apple's products.",
    no_of_positions: 3,
    employment_type: "Full-time",
    years_of_experience: 4,
    salary: 2200000,
    work_mode: "Hybrid",
  },
  {
    company_name: "Flipkart",
    location: "Chennai ",
    job_title: "Software Development Engineer",
    job_description: "Develop scalable and efficient systems for e-commerce.",
    no_of_positions: 4,
    employment_type: "Full-time",
    years_of_experience: 2,
    salary: 1200000,
    work_mode: "Work from Home",
  },
  {
    company_name: "IBM",
    location: "Mumbai ",
    job_title: "AI Software Developer",
    job_description: "Develop AI-driven solutions for enterprise clients.",
    no_of_positions: 3,
    employment_type: "Full-time",
    years_of_experience: 5,
    salary: 2500000,
    work_mode: "Hybrid",
  },
  {
    company_name: "Meta",
    location: "Bangalore ",
    job_title: "Backend Engineer",
    job_description:
      "Develop backend systems and APIs for scalable applications.",
    no_of_positions: 3,
    employment_type: "Full-time",
    years_of_experience: 3,
    salary: 2000000,
    work_mode: "Office",
  },
  {
    company_name: "Microsoft",
    location: "Chennai ",
    job_title: "Software Engineer",
    job_description: "Design and implement software solutions for customers.",
    no_of_positions: 5,
    employment_type: "Full-time",
    years_of_experience: 2,
    salary: 1600000,
    work_mode: "Hybrid",
  },
  {
    company_name: "Nvidia",
    location: "Hyderabad ",
    job_title: "GPU Software Engineer",
    job_description: "Optimize GPU software for performance and functionality.",
    no_of_positions: 2,
    employment_type: "Full-time",
    years_of_experience: 4,
    salary: 2400000,
    work_mode: "Hybrid",
  },
  {
    company_name: "Qualcomm",
    location: "Bangalore ",
    job_title: "Wireless Communication Engineer",
    job_description:
      "Develop solutions for wireless communication technologies.",
    no_of_positions: 3,
    employment_type: "Full-time",
    years_of_experience: 3,
    salary: 1800000,
    work_mode: "Office",
  },
];

export default jobData;
